version: '3.9'
services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "jffrancob/wa-multidevice:0.0.12"
    command: --os=Linux --debug true
    environment:
      - SERVER_URL=http://${API_HOST-localhost}:${API_PORT-3000}
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: 'always'
    ports:
      - "3000:3000"