services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "jffrancob/wa-multidevice:${WAMD_VERSION?No version defined}"
    environment:
      - SERVER_URL=http://${API_HOST-localhost}:${API_PORT-3000}
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: "on-failure"
    ports:
      - "3000:3000"
    env_file:
      - src/.env